import type { UltravoucherVoucher } from "@/app/types/ultravoucher";

export const MOCK_VOUCHERS: UltravoucherVoucher[] = [
  {
    id: "mock-01",
    name: "Indomaret Rp 25.000",
    price: 25000,
    image: "https://via.placeholder.com/800x400?text=Indomaret+25K",
    clientName: "Indomaret",
    merchantCode: "indmr",
    stockAvailable: 120,
    voucherPrices: [],
  },
  {
    id: "mock-02",
    name: "Indomaret Rp 50.000",
    price: 50000,
    image: "https://via.placeholder.com/800x400?text=Indomaret+50K",
    clientName: "Indomaret",
    merchantCode: "indmr",
    stockAvailable: 80,
    voucherPrices: [],
  },
  {
    id: "mock-03",
    name: "Alfamart Rp 25.000",
    price: 25000,
    image: "https://via.placeholder.com/800x400?text=Alfamart+25K",
    clientName: "Alfamart",
    merchantCode: "alfamart",
    stockAvailable: 150,
    voucherPrices: [],
  },
  {
    id: "mock-04",
    name: "Alfamart Rp 100.000",
    price: 100000,
    image: "https://via.placeholder.com/800x400?text=Alfamart+100K",
    clientName: "Alfamart",
    merchantCode: "alfamart",
    stockAvailable: 60,
    voucherPrices: [],
  },
  {
    id: "mock-05",
    name: "Traveloka Rp 50.000",
    price: 50000,
    image: "https://via.placeholder.com/800x400?text=Traveloka+50K",
    clientName: "Traveloka",
    merchantCode: "traveloka",
    stockAvailable: 90,
    voucherPrices: [],
  },
  {
    id: "mock-06",
    name: "Traveloka Rp 100.000",
    price: 100000,
    image: "https://via.placeholder.com/800x400?text=Traveloka+100K",
    clientName: "Traveloka",
    merchantCode: "traveloka",
    stockAvailable: 45,
    voucherPrices: [],
  },
  {
    id: "mock-07",
    name: "GrabFood Rp 25.000",
    price: 25000,
    image: "https://via.placeholder.com/800x400?text=GrabFood+25K",
    clientName: "Grab",
    merchantCode: "grab",
    stockAvailable: 110,
    voucherPrices: [],
  },
  {
    id: "mock-08",
    name: "Grab Rp 100.000",
    price: 100000,
    image: "https://via.placeholder.com/800x400?text=Grab+100K",
    clientName: "Grab",
    merchantCode: "grab",
    stockAvailable: 35,
    voucherPrices: [],
  },
  {
    id: "mock-09",
    name: "Gojek Rp 20.000",
    price: 20000,
    image: "https://via.placeholder.com/800x400?text=Gojek+20K",
    clientName: "Gojek",
    merchantCode: "gojek",
    stockAvailable: 0,
    voucherPrices: [],
  },
  {
    id: "mock-10",
    name: "Gojek Rp 50.000",
    price: 50000,
    image: "https://via.placeholder.com/800x400?text=Gojek+50K",
    clientName: "Gojek",
    merchantCode: "gojek",
    stockAvailable: 70,
    voucherPrices: [],
  },
];
